const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../../.env') });
const mongoose = require('mongoose');
const Movie = require('../models/Movie');
const Theatre = require('../models/Theatre');
const User = require('../models/User');

// Import data from data.js
const MOVIES_DATA = [
    { id: 1, title: "They Call Him OG", genre: "Action", language: "Telugu", format: "2D", rating: 7.3, duration: 154, age: "A", year: 2024, img: "trailers/og1.jpg", description: "They Call Him OG unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "New", trailer: "", cast: ["Pawan Kalyan", "Emraan Hashmi", "Priyanka Arul Mohan", "Arjun Das", "Sriya Reddy"] },
    { id: 2, title: "Mirai", genre: "Sci-Fi", language: "Telugu", format: "3D", rating: 7.8, duration: 169, age: "UA", year: 2024, img: "trailers/mirai1.jpeg", description: "Mirai unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "3D", trailer: "", cast: ["Teja Sajja", "Ritika Nayak", "Sathyaraj", "Rajeev Kanakala", "Harsha Chemudu"] },
    { id: 3, title: "Ghaati", genre: "Crime", language: "Telugu", format: "2D", rating: 6.6, duration: 155, age: "UA", year: 2024, img: "trailers/ghaati1.jpg", description: "Ghaati unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "", trailer: "", cast: ["Anushka Shetty", "Indrajith Sukumaran", "Srinivas Avasarala", "Ajay Ghosh", "Harsha Vardhan"] },
    { id: 4, title: "Subham", genre: "Horror", language: "Telugu", format: "2D", rating: 6.2, duration: 125, age: "UA", year: 2024, img: "trailers/subham1.jpg", description: "Subham unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "", trailer: "", cast: ["Sree Vishnu", "Priyadarshi", "Faria Abdullah", "Viva Harsha", "Ajay"] },
    { id: 5, title: "Laila", genre: "Comedy", language: "Telugu", format: "2D", rating: 5.8, duration: 136, age: "UA", year: 2024, img: "trailers/laila1.jpg", description: "Laila unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "", trailer: "", cast: ["Tamannaah Bhatia", "Sidhu Jonnalagadda", "Vennela Kishore", "Vidyullekha Raman", "Ajay Kumar"] },
    { id: 6, title: "Badmashulu", genre: "Comedy", language: "Telugu", format: "2D", rating: 6.0, duration: 158, age: "U", year: 2024, img: "trailers/badmashulu1.jpg", description: "Badmashulu unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "", trailer: "", cast: ["Allari Naresh", "Sunil", "Saptagiri", "Hyper Aadi", "Chandini Chowdary"] },
    { id: 7, title: "Gopi Galla Goa Trip", genre: "Drama", language: "Telugu", format: "2D", rating: 7.1, duration: 142, age: "UA", year: 2024, img: "trailers/gopi galla goa trip1.jpg", description: "Gopi Galla Goa Trip unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "", trailer: "", cast: ["Suhas", "Harsha Chemudu", "Viva Harsha", "Abhinav Gomatam", "Priya Vadlamani"] },
    { id: 8, title: "K-Ramp", genre: "Comedy", language: "Telugu", format: "2D", rating: 6.4, duration: 141, age: "UA", year: 2024, img: "trailers/kramp1.jpg", description: "Romantic Comedy, Drama", badge: "", trailer: "", cast: ["Kiran Abbavaram", "Priyanka Jawalkar", "Sudarshan", "Brahmaji", "Praveen"] },
    { id: 9, title: "Telusu Kada", genre: "Romance", language: "Telugu", format: "2D", rating: 7.4, duration: 140, age: "UA", year: 2024, img: "trailers/telsukada1.jpg", description: "Telusu Kada unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "", trailer: "", cast: ["Siddu Jonnalagadda", "Raashi Khanna", "Ali", "Tanikella Bharani", "Rohini"] },
    { id: 10, title: "Mass Jathara", genre: "Action", language: "Telugu", format: "IMAX", rating: 7.0, duration: 152, age: "UA", year: 2024, img: "trailers/mass jathara1.jpg", description: "Mass Jathara unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "IMAX", trailer: "", cast: ["Vishwak Sen", "Neha Shetty", "Rao Ramesh", "Ajay", "Hyper Aadi"] },
    { id: 11, title: "Premante", genre: "Romance", language: "Telugu", format: "2D", rating: 7.2, duration: 138, age: "U", year: 2024, img: "trailers/premante1.jpeg", description: "Premante unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "", trailer: "", cast: ["Anand Deverakonda", "Vaishnavi Chaitanya", "Harsha Chemudu", "Abhinav Gomatam", "Rajeev Kanakala"] },
    { id: 12, title: "Andhela Ravamidhi", genre: "Musical", language: "Telugu", format: "2D", rating: 7.5, duration: 141, age: "U", year: 2024, img: "trailers/andhela1.avif", description: "Andhela Ravamidhi unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "", trailer: "", cast: ["Vijay Deverakonda", "Krithi Shetty", "Sunil", "Brahmaji", "Nassar"] },
    { id: 13, title: "Shashtipoorthi", genre: "Drama", language: "Telugu", format: "2D", rating: 6.8, duration: 130, age: "U", year: 2024, img: "trailers/shashtipoorti1.webp", description: "Shashtipoorthi unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "", trailer: "", cast: ["Rajendra Prasad", "Naresh", "Suhasini", "Brahmanandam", "Prudhvi Raj"] },
    { id: 14, title: "Uppu Kappurambu", genre: "Comedy", language: "Telugu", format: "2D", rating: 7.6, duration: 136, age: "U", year: 2024, img: "trailers/uppu1.jpg", description: "Uppu Kappurambu unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "Hit", trailer: "", cast: ["Suhas", "Rukshar Dhillon", "Vennela Kishore", "Viva Harsha", "Satyam Rajesh"] },
    { id: 15, title: "14", genre: "Mystery", language: "Telugu", format: "2D", rating: 7.0, duration: 148, age: "UA", year: 2024, img: "trailers/14-1.jpg", description: "14 unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "", trailer: "", cast: ["Nikhil Siddhartha", "Anupama Parameswaran", "Ajay", "Tulasi", "Kalpalatha"] },
    { id: 16, title: "Avatar: Fire and Ash", genre: "Sci-Fi", language: "English", format: "3D", rating: 8.2, duration: 160, age: "UA", year: 2025, img: "trailers/avatar1.webp", description: "Avatar: Fire and Ash unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "2025", trailer: "", cast: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver", "Stephen Lang", "Kate Winslet"] },
    { id: 17, title: "How to Train Your Dragon", genre: "Fantasy", language: "English", format: "2D", rating: 7.9, duration: 125, age: "U", year: 2025, img: "trailers/how to train your dragon1.webp", description: "How to Train Your Dragon unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "Live Action", trailer: "", cast: ["Mason Thames", "Nico Parker", "Gerard Butler", "Nick Frost", "Julian Dennison"] },
    { id: 18, title: "The Running Man", genre: "Action", language: "English", format: "2D", rating: 7.3, duration: 133, age: "A", year: 2025, img: "trailers/runningman1.jpg", description: "The Running Man unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "", trailer: "", cast: ["Glen Powell", "Will Poulter", "Ben Barnes", "Giancarlo Esposito", "Saoirse Ronan"] },
    { id: 19, title: "The SpongeBob Movie: Search for SquarePants", genre: "Animation", language: "English", format: "2D", rating: 7.1, duration: 96, age: "U", year: 2025, img: "trailers/spongebob1.webp", description: "The SpongeBob Movie: Search for SquarePants unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "", trailer: "", cast: ["Tom Kenny", "Bill Fagerbakke", "Clancy Brown", "Mr. Lawrence", "Rodger Bumpass"] },
    { id: 20, title: "The Fantastic Four: First Steps", genre: "Superhero", language: "English", format: "IMAX", rating: 7.0, duration: 135, age: "UA", year: 2025, img: "trailers/fantastic4-1.jpeg", description: "The Fantastic Four: First Steps unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "Marvel", trailer: "", cast: ["Pedro Pascal", "Vanessa Kirby", "Joseph Quinn", "Ebon Moss-Bachrach", "Ralph Ineson"] },
    { id: 21, title: "Wicked: For Good", genre: "Musical", language: "English", format: "2D", rating: 7.4, duration: 135, age: "UA", year: 2025, img: "trailers/wicked1.webp", description: "Wicked: For Good unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "", trailer: "", cast: ["Cynthia Erivo", "Ariana Grande", "Jonathan Bailey", "Jeff Goldblum", "Michelle Yeoh"] },
    { id: 22, title: "Scream 7", genre: "Horror", language: "English", format: "2D", rating: 6.8, duration: 110, age: "A", year: 2025, img: "trailers/scream7-1.jpg", description: "Scream 7 unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "", trailer: "", cast: ["Neve Campbell", "Courteney Cox", "Mason Gooding", "Jasmin Savoy Brown", "Hayden Panettiere"] },
    { id: 23, title: "Anaconda", genre: "Adventure", language: "English", format: "2D", rating: 6.5, duration: 120, age: "A", year: 2025, img: "trailers/anaconda1.jpg", description: "Anaconda unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "", trailer: "", cast: ["Paul Rudd", "Jack Black", "Thandiwe Newton", "Winston Duke", "Jenna Ortega"] },
    { id: 24, title: "Jurassic World: Rebirth", genre: "Sci-Fi", language: "English", format: "IMAX", rating: 7.6, duration: 145, age: "UA", year: 2025, img: "trailers/jurassic world1.jpg", description: "Jurassic World: Rebirth unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "IMAX", trailer: "", cast: ["Chris Pratt", "Bryce Dallas Howard", "Justice Smith", "Isabella Sermon", "Jeff Goldblum"] },
    { id: 25, title: "Mission: Impossible – The Final Reckoning", genre: "Action", language: "English", format: "IMAX", rating: 7.8, duration: 150, age: "UA", year: 2025, img: "trailers/mission impossible1.jpg", description: "Action, Espionage, Thriller | Cast: Tom Cruise, Hayley Atwell", badge: "Finale", trailer: "", cast: ["Tom Cruise", "Hayley Atwell", "Simon Pegg", "Rebecca Ferguson", "Ving Rhames"] },
    { id: 26, title: "F1", genre: "Sport", language: "English", format: "IMAX", rating: 7.2, duration: 130, age: "UA", year: 2025, img: "trailers/F1-1.jpg", description: "F1 unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "", trailer: "", cast: ["Brad Pitt", "Damson Idris", "Javier Bardem", "Kerry Condon", "Tobias Menzies"] },
    { id: 27, title: "The Conjuring: Last Rites", genre: "Horror", language: "English", format: "2D", rating: 6.9, duration: 115, age: "A", year: 2025, img: "trailers/conjuring1.jpg", description: "The Conjuring: Last Rites unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "", trailer: "", cast: ["Patrick Wilson", "Vera Farmiga", "Sterling Jerins", "Ruairi O'Connor", "Ingrid Bisu"] },
    { id: 28, title: "Die My Love", genre: "Drama", language: "English", format: "2D", rating: 7.0, duration: 130, age: "A", year: 2025, img: "trailers/die my love1.jpg", description: "Die My Love unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "", trailer: "", cast: ["Jennifer Lawrence", "Robert Pattinson", "Mia Goth", "Jesse Plemons", "LaKeith Stanfield"] },
    { id: 29, title: "Predator: Badlands", genre: "Sci-Fi", language: "English", format: "2D", rating: 6.7, duration: 125, age: "A", year: 2025, img: "trailers/predator1.jpg", description: "Predator: Badlands unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "", trailer: "", cast: ["Boyd Holbrook", "Elle Fanning", "Sterling K. Brown", "Mahershala Ali", "Wyatt Russell"] },
    { id: 30, title: "Wake Up Dead Man: A Knives Out Mystery", genre: "Mystery", language: "English", format: "2D", rating: 7.3, duration: 140, age: "UA", year: 2025, img: "trailers/wake up dead man1.jpg", description: "Wake Up Dead Man: A Knives Out Mystery unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "", trailer: "", cast: ["Daniel Craig", "Josh O'Connor", "Cailee Spaeny", "Glenn Close", "Andrew Scott"] },
    { id: 31, title: "Alpha", genre: "Action", language: "Hindi", format: "2D", rating: 7.5, duration: 145, age: "UA", year: 2025, img: "trailers/Alpha.jpg", description: "Alpha unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "YRF", trailer: "trailers/SSYouTube.online_Alpha  Official Trailer Alia  Sharvari  Shiv Rawail Aditya Chopra Bobby Deol YRF Spy Universe_720p.mp4", cast: ["Alia Bhatt", "Sharvari Wagh", "Bobby Deol", "Aditya Roy Kapur", "Jaideep Ahlawat"] },
    { id: 32, title: "Dhurandhar", genre: "Action", language: "Hindi", format: "IMAX", rating: 8.0, duration: 155, age: "UA", year: 2025, img: "trailers/dhurandar.jpg", description: "Dhurandhar unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "IMAX", trailer: "trailers/SSYouTube.online_Dhurandhar Official Trailer  Ranveer Singh  Aditya Dhar  In Cinemas 5th December 2025_720p.mp4", cast: ["Ranveer Singh", "Sanjay Dutt", "Arjun Rampal", "R. Madhavan", "Akshaye Khanna"] },
    { id: 33, title: "HAQ", genre: "Thriller", language: "Hindi", format: "2D", rating: 7.4, duration: 138, age: "UA", year: 2025, img: "trailers/haq.jpg", description: "HAQ unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "New", trailer: "trailers/SSYouTube.online_HAQ  Official Trailer  Yami Gautam Dhar, Emraan Hashmi  Suparn S Varma  In Cinemas 7th Nov_720p.mp4", cast: ["Yami Gautam", "Emraan Hashmi", "Jaideep Ahlawat", "Sharad Kelkar", "Kumud Mishra"] },
    { id: 34, title: "Ikkis", genre: "War", language: "Hindi", format: "2D", rating: 7.8, duration: 150, age: "UA", year: 2025, img: "trailers/ikkis.jpg", description: "Ikkis unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "Christmas", trailer: "trailers/SSYouTube.online_Ikkis - Official Trailer  In Cinemas Worldwide This Christmas  25th December 2025_720p.mp4", cast: ["Agastya Nanda", "Dharmendra", "Jaideep Ahlawat", "Mrunal Thakur", "Raj Zutshi"] },
    { id: 35, title: "Jatadhara", genre: "Action", language: "Hindi", format: "2D", rating: 7.2, duration: 142, age: "UA", year: 2025, img: "trailers/Jatadhara-001.jpg", description: "Jatadhara unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "New", trailer: "trailers/SSYouTube.online_JATADHARA Official Hindi Trailer  Sudheer Babu  Sonakshi Sinha  Prerna Arora  In Cinemas 7 Nov_720p.mp4", cast: ["Sudheer Babu", "Sonakshi Sinha", "Ravi Kishan", "Prakash Raj", "Raj Arjun"] },
    { id: 36, title: "Krrish 4: Jaadu Returns", genre: "Superhero", language: "Hindi", format: "IMAX", rating: 8.2, duration: 165, age: "UA", year: 2025, img: "trailers/krissh 4.jpg", description: "Krrish 4: Jaadu Returns unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "IMAX", trailer: "trailers/SSYouTube.online_KRRISH 4 Jaadu Returns - Trailer  Hrithik Roshan  Bobby Deol  Tiger Shroff, Amitabh B  In 2025_720p.mp4", cast: ["Hrithik Roshan", "Tiger Shroff", "Bobby Deol", "Amitabh Bachchan", "Nora Fatehi"] },
    { id: 37, title: "120 Bahadur", genre: "War", language: "Hindi", format: "2D", rating: 7.6, duration: 148, age: "UA", year: 2025, img: "trailers/bahadur.jpg", description: "120 Bahadur unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "21 Nov", trailer: "trailers/SSYouTube.online_120 Bahadur  Official Teaser  Farhan Akhtar  Raashii Khanna  21st November_720p.mp4", cast: ["Farhan Akhtar", "Raashii Khanna", "Aditya Seal", "Pankaj Tripathi", "Amruta Subhash"] },
    { id: 38, title: "De De Pyaar De 2", genre: "Comedy", language: "Hindi", format: "2D", rating: 7.0, duration: 135, age: "UA", year: 2025, img: "trailers/de de pyar de.jpg", description: "De De Pyaar De 2 unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "14 Nov", trailer: "trailers/SSYouTube.online_De De Pyaar De 2 - Official Trailer  Ajay Devgn, R. Madhavan, Rakul Preet, Meezaan Jafri  14th Nov_720p.mp4", cast: ["Ajay Devgn", "Rakul Preet Singh", "R. Madhavan", "Meezaan Jafri", "Seema Pahwa"] },
    { id: 39, title: "Gustaakh Ishq", genre: "Romance", language: "Hindi", format: "2D", rating: 6.9, duration: 132, age: "UA", year: 2025, img: "trailers/gustaakh.webp", description: "Gustaakh Ishq unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "", trailer: "trailers/SSYouTube.online_Gustaakh Ishq - Official Trailer  Naseeruddin Shah, Vijay Varma, Fatima Sana Shaikh, Sharib Hashmi_720p.mp4", cast: ["Vijay Varma", "Fatima Sana Shaikh", "Naseeruddin Shah", "Sharib Hashmi", "Aditi Rao Hydari"] },
    { id: 40, title: "Kis Kisko Pyaar Karoon 2", genre: "Comedy", language: "Hindi", format: "2D", rating: 6.5, duration: 128, age: "UA", year: 2025, img: "trailers/kis kiso pyar.webp", description: "Kis Kisko Pyaar Karoon 2 unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "", trailer: "trailers/SSYouTube.online_KIS KISKO PYAAR KAROON 2 - Official Trailer  Kapil Sharma  Jacqueline Fernandez  T-Series_720p.mp4", cast: ["Kapil Sharma", "Jacqueline Fernandez", "Varun Sharma", "Kiku Sharda", "Sonu Nigam"] },
    { id: 41, title: "Masti 4", genre: "Comedy", language: "Hindi", format: "2D", rating: 6.8, duration: 130, age: "A", year: 2025, img: "trailers/masti 4.jpg", description: "Masti 4 unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "21 Nov", trailer: "trailers/SSYouTube.online_Masti 4 - Official Teaser  Riteish Deshmukh  Vivek Oberoi  Aftab Shivdasani  21st Nov_720p.mp4", cast: ["Riteish Deshmukh", "Vivek Oberoi", "Aftab Shivdasani", "Nora Fatehi", "Sonnalli Seygall"] },
    { id: 42, title: "Tere Ishk Mein", genre: "Romance", language: "Hindi", format: "2D", rating: 7.3, duration: 140, age: "UA", year: 2025, img: "trailers/tere ishk mein1.jpg", description: "Tere Ishk Mein unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "ARR", trailer: "trailers/SSYouTube.online_TERE ISHK MEIN TEASER (Hindi)  Dhanush, Kriti Sanon  A. R. Rahman  Aanand L Rai  Bhushan Kumar_720p.mp4", cast: ["Dhanush", "Kriti Sanon", "Radhika Apte", "Vijay Sethupathi", "Sushant Singh"] },
    { id: 43, title: "Break The Silence", genre: "Thriller", language: "Hindi", format: "2D", rating: 6.7, duration: 125, age: "UA", year: 2025, img: "trailers/break the silence.webp", description: "Break The Silence unfolds like a high-voltage cinematic storm, opening with a striking setup that throws its protagonist into a world of rising danger, emotional turbulence, and unstoppable momentum. The film blends sweeping visuals with mounting tension as the hero faces forces far greater than themselves—ruthless enemies, hidden truths, and inner conflicts waiting to ignite. Every chapter raises the stakes, pulling the character deeper into a journey of transformation filled with atmospheric landscapes, charged confrontations, and heart‑pounding revelations. As alliances shift and the path narrows, the protagonist must confront a defining choice that will carve their destiny. Driven by adrenaline, emotion, and cinematic flair, the story races toward a sharp, resonant climax that leaves the audience breathless while hinting at deeper mysteries beyond the frame.", badge: "", trailer: "trailers/SSYouTube.online_Break The Silence - Official Teaser  Anupriya Goenka, Yukti Kapoor, Rohit Pathak_720p.mp4", cast: ["Vicky Kaushal", "Tripti Dimri", "Manoj Bajpayee", "Sayani Gupta", "Ashutosh Rana"] }
];

const THEATRES_DATA = [
    { id: 1, name: "Shanti Theatre", screens: 1, screenId: "SHHY01", location: "Narayanguda" },
    { id: 2, name: "Deepak 70mm", screens: 1, screenId: "DPHY70", location: "Narayanguda Main Rd" },
    { id: 3, name: "Sapna Theatre", screens: 1, screenId: "SPNHY01", location: "Abids / Koti" },
    { id: 4, name: "Asia Theatre", screens: 1, screenId: "ASHY01", location: "RTC X Roads" },
    { id: 5, name: "Sri Mayuri 70mm", screens: 1, screenId: "SMY70", location: "Musheerabad / RTC X Roads" },
    { id: 6, name: "Sudha 70mm", screens: 1, screenId: "SDH70", location: "Abids" },
    { id: 7, name: "Santosh Theatre", screens: 1, screenId: "SNSH01", location: "Abids / Koti" },
    { id: 8, name: "Sree Rama Theatre", screens: 1, screenId: "SRMHY01", location: "Amberpet" },
    { id: 9, name: "Prasads Multiplex (IMAX + PCX)", screens: 6, screenId: "PRIMX06", location: "Necklace Road / Khairatabad" },
    { id: 10, name: "INOX GVK One", screens: 6, screenId: "INGK06", location: "Banjara Hills" },
    { id: 11, name: "PVR RK Cineplex", screens: 4, screenId: "PVRRK04", location: "Road No. 2, Banjara Hills" },
    { id: 12, name: "Asian Lakshmikala", screens: 4, screenId: "ASLKL04", location: "Moosapet" },
    { id: 13, name: "Cinepolis Mantra Mall", screens: 5, screenId: "CNPMM05", location: "Moosapet / Asif Nagar" },
    { id: 14, name: "INOX Maheshwari Parmeshwari", screens: 4, screenId: "INMP04", location: "Kachiguda / RTC X Roads" },
    { id: 15, name: "Asian Ganga Theatre", screens: 3, screenId: "ASGNG03", location: "Dilsukhnagar" },
    { id: 16, name: "Cinepolis CCPL Mall", screens: 5, screenId: "CNPCP05", location: "Malkajgiri" },
    { id: 17, name: "Sudharshan 35mm", screens: 1, screenId: "SDS35", location: "RTC X Roads" },
    { id: 18, name: "Sree Annapurna Theatre", screens: 1, screenId: "SAPN01", location: "Boduppal" },
    { id: 19, name: "PVR Irrum Manzil (Next Galleria)", screens: 7, screenId: "PVRIM07", location: "Ameerpet" },
    { id: 20, name: "PVR Panjagutta", screens: 6, screenId: "PVRPG06", location: "Panjagutta" },
    { id: 21, name: "INOX Punjagutta City Center", screens: 6, screenId: "INPCC06", location: "Punjagutta" },
    { id: 22, name: "PVR Inorbit Mall", screens: 8, screenId: "PVRIO08", location: "Hitech City" },
    { id: 23, name: "AMB Cinemas", screens: 7, screenId: "AMBJB07", location: "Gachibowli" },
    { id: 24, name: "Asian CineTown Uppal", screens: 5, screenId: "ASUPL05", location: "Uppal" },
    { id: 25, name: "Cinepolis DSL Virtue Mall", screens: 6, screenId: "CNPDL06", location: "Dilsukhnagar" },
    { id: 26, name: "Moviemax Ameerpet", screens: 4, screenId: "MMAMP04", location: "Ameerpet" },
    { id: 27, name: "Asian Jyothi Theatre", screens: 2, screenId: "ASJYT02", location: "L. B. Nagar" },
    { id: 28, name: "Cinetown Gachibowli", screens: 5, screenId: "CNGKB05", location: "Gachibowli" },
    { id: 29, name: "CINEMAX Kukatpally", screens: 5, screenId: "CMXKP05", location: "Kukatpally" },
    { id: 30, name: "PVR Sujana Mall", screens: 8, screenId: "PVRSJ08", location: "Kukatpally / KPHB" }
];

const seedDatabase = async () => {
    try {
        // Connect to MongoDB
        await mongoose.connect(process.env.MONGO_URI, {
            useNewUrlParser: true,
            useUnifiedTopology: true
        });

        console.log('Connected to MongoDB');

        // Clear existing data
        await Movie.deleteMany({});
        await Theatre.deleteMany({});
        await User.deleteMany({});
        console.log('Cleared existing data');

        // Transform and insert movies (remove id field, MongoDB will generate _id)
        const movies = MOVIES_DATA.map(({ id, ...rest }) => rest);
        await Movie.insertMany(movies);
        console.log(`✓ Inserted ${movies.length} movies`);

        // Transform and insert theatres
        const theatres = THEATRES_DATA.map(({ id, ...rest }) => ({
            ...rest,
            seatConfiguration: {
                rows: 10,
                cols: 12,
                aisles: [4, 9] // Example aisles
            }
        }));
        await Theatre.insertMany(theatres);
        console.log(`✓ Inserted ${theatres.length} theatres`);

        // Create Default Users
        const users = [
            {
                name: 'Admin User',
                email: 'admin@example.com',
                password: 'password123',
                role: 'admin',
                phone: '9999999999',
                emailVerified: true
            },
            {
                name: 'John Doe',
                email: 'user@example.com',
                password: 'password123',
                role: 'user',
                phone: '8888888888',
                emailVerified: true
            }
        ];

        // We use create instead of insertMany to trigger pre('save') middleware for password hashing
        for (const user of users) {
            await User.create(user);
        }
        console.log(`✓ Inserted ${users.length} users (Admin & Standard)`);

        // Create indexes
        await Movie.createIndexes();
        await Theatre.createIndexes();
        console.log('✓ Created indexes');

        // Clear Redis Cache
        const redis = require('redis');
        const redisClient = redis.createClient({
            url: process.env.REDIS_URL || 'redis://localhost:6379'
        });

        redisClient.on('error', err => console.log('Redis Client Error', err));

        await redisClient.connect();
        await redisClient.flushAll();
        console.log('✓ Cleared Redis cache');
        await redisClient.disconnect();

        // Create showtimes for the next 3 days
        const showtimes = [];
        const now = new Date();
        const movieDocs = await Movie.find();
        const theatreDocs = await Theatre.find();

        if (movieDocs.length > 0 && theatreDocs.length > 0) {
            // Create showtimes for ALL movies
            for (let i = 0; i < movieDocs.length; i++) {
                const movie = movieDocs[i];

                // Determine number of theatres based on rating (min 5, max all theatres)
                // Higher rating = more theatres. 
                // Example: Rating 8.0 -> ~12 theatres, Rating 6.0 -> ~9 theatres.
                // Base count 5, plus rating * 1.5
                const theatreCount = Math.min(
                    theatreDocs.length,
                    Math.max(5, Math.floor(5 + (movie.rating || 5) * 1.5))
                );

                // Pick random theatres for each movie
                const randomTheatres = theatreDocs
                    .sort(() => 0.5 - Math.random())
                    .slice(0, theatreCount);

                for (const theatre of randomTheatres) {
                    // Create 2 showtimes per day for 3 days
                    for (let d = 0; d < 3; d++) {
                        for (let t = 0; t < 2; t++) {
                            const startTime = new Date(now);
                            startTime.setDate(startTime.getDate() + d);
                            // Random start times between 10 AM and 10 PM
                            const hour = 10 + Math.floor(Math.random() * 12);
                            startTime.setHours(hour, 0, 0, 0);

                            // Generate seats
                            const seats = [];
                            const { rows, cols } = theatre.seatConfiguration || { rows: 10, cols: 10 };
                            const rowLabels = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'];

                            for (let r = 0; r < rows; r++) {
                                const rowLabel = rowLabels[r] || `R${r + 1}`;
                                for (let c = 1; c <= cols; c++) {
                                    seats.push({
                                        row: rowLabel,
                                        number: c,
                                        status: 'Available'
                                    });
                                }
                            }

                            showtimes.push({
                                movie: movie._id,
                                theatre: theatre._id,
                                startTime,
                                endTime: new Date(startTime.getTime() + movie.duration * 60000),
                                price: 150 + Math.floor(Math.random() * 100),
                                screen: Math.floor(Math.random() * theatre.screens) + 1,
                                seats
                            });
                        }
                    }
                }
            }

            const Showtime = require('../models/Showtime');
            await Showtime.deleteMany({});
            await Showtime.insertMany(showtimes);
            console.log(`✓ Inserted ${showtimes.length} showtimes`);
        }

        console.log('\n✅ Database seeding completed successfully!');
        console.log(`\nSummary:`);
        console.log(`- Movies: ${movies.length}`);
        console.log(`- Theatres: ${theatres.length}`);
        console.log(`- Showtimes: ${showtimes.length}`);

        process.exit(0);
    } catch (error) {
        console.error('❌ Error seeding database:', error);
        process.exit(1);
    }
};

seedDatabase();
